name: ca_env
channels:
- conda-forge
dependencies:
- python=3.10
- napari
- magicgui
- qtpy
- numpy<=1.24.2
- pandas
- scikit-image
- scikit-learn
- scipy
- cudatoolkit=11.2
- cudnn=8.1.0
- matplotlib
- seaborn
- opencv
- natsort
- notebook
- ipykernel
- pip
- nomkl
- pip:
  - cellpose==3.1.1.1
  - stardist==0.9.1
  - pca
  - napari-blob-detection==0.0.2
  - csbdeep
  - tensorflow<2.11
